domain: "kong.example"
ingress_class_name: "kong"
cert_secret_name: "kong-ingress-ssl-cert"
namespace: kong-ingress-routes
global:
  ingress_annotations:
    konghq.com/preserve-host: "true"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"

ingress:
  apiservice:
    name: apiservice
    namespace: api-service
    path_type: "ImplementationSpecific"
    service_name: "api-service"
    domains: []
    annotations: {}
    service_port: 3000
    paths:
      - path: "/"
  
