domain: &domain ""
ingress_class_name: "kong"
cert_secret_name: "kong-ingress-ssl-cert"
namespace: &namespace aml-dev
global:
  domain: *domain
  namespace: *namespace
  ingress_annotations:
    konghq.com/preserve-host: "true"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"

ingress:
  apiservice:
    name: api-service
    namespace: aml-dev
    path_type: "ImplementationSpecific"
    service_name: "api-service"
    domains: []
    annotations: {}
    service_port: 3001
    paths:
      - path: "/"
  
